services:
  dev-db:
    image: postgres:13
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp

volumes:
  db_data:
networks:
  freecodecamp:
